### ISSUE TITLE
Editor doesn't get called

### ISSUE THREAD

**Issue by Wesley-Chan** [icewind1991/files_markdown#94]
Operation: Create a file with the extension ".md" and click it.

Expected: Markdown editor shows up.

Actually happened: File downloading dialogue shows up.

Browser: FireFox 52.6.0 (64-bit) on Gentoo

Nextcloud: 13.0.0

Host Machine: Ubuntu Server 17.10

**Comment by icewind1991** [comment]
As described in the readme, the Nextcloud text editor is required.

If you do have the text editor installed and are still having this issue then please open an issue there

**Comment by Erriez** [comment]
>As described in the readme, the Nextcloud text editor is required.
In Nextcloud version 18.0.1, the build-in text editor is started when opening a .md file instead of this Markdown editor.

> If you do have the text editor installed and are still having this issue then please open an issue there
I've installed this Markdown Editor v2.2.0 via the Apps menu. The default Text Editor v2.0.0 is enabled.

I tried a logout/login/reboot etc, but could not get it up and running. Any idea?
